AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    KMSAlias:
        Type: "AWS::KMS::Alias"
        Properties:
            AliasName: "alias/ECS_KEY"
            TargetKeyId: !Ref KMSKey

    KMSKey:
        Type: "AWS::KMS::Key"
        Properties:
            Enabled: true
            Description: ""
            KeyUsage: "ENCRYPT_DECRYPT"
            KeyPolicy: !Sub |
                {
                  "Version" : "2012-10-17",
                  "Id" : "key-consolepolicy-3",
                  "Statement" : [ {
                    "Sid" : "Enable IAM User Permissions",
                    "Effect" : "Allow",
                    "Principal" : {
                      "AWS" : "arn:aws:iam::${AWS::AccountId}:root"
                    },
                    "Action" : "kms:*",
                    "Resource" : "*"
                  }, {
                    "Sid" : "Allow access for Key Administrators",
                    "Effect" : "Allow",
                    "Principal" : {
                      "AWS" : "arn:aws:iam::${AWS::AccountId}:user/drakeg"
                    },
                    "Action" : [ "kms:Create*", "kms:Describe*", "kms:Enable*", "kms:List*", "kms:Put*", "kms:Update*", "kms:Revoke*", "kms:Disable*", "kms:Get*", "kms:Delete*", "kms:TagResource", "kms:UntagResource", "kms:ScheduleKeyDeletion", "kms:CancelKeyDeletion" ],
                    "Resource" : "*"
                  }, {
                    "Sid" : "Allow use of the key",
                    "Effect" : "Allow",
                    "Principal" : {
                      "AWS" : [ "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS", "arn:aws:iam::${AWS::AccountId}:user/drakeg", "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.amazonaws.com/AWSServiceRoleForECS" ]
                    },
                    "Action" : [ "kms:Encrypt", "kms:Decrypt", "kms:ReEncrypt*", "kms:GenerateDataKey*", "kms:DescribeKey" ],
                    "Resource" : "*"
                  }, {
                    "Sid" : "Allow attachment of persistent resources",
                    "Effect" : "Allow",
                    "Principal" : {
                      "AWS" : [ "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/eks.amazonaws.com/AWSServiceRoleForAmazonEKS", "arn:aws:iam::${AWS::AccountId}:user/drakeg", "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.amazonaws.com/AWSServiceRoleForECS" ]
                    },
                    "Action" : [ "kms:CreateGrant", "kms:ListGrants", "kms:RevokeGrant" ],
                    "Resource" : "*",
                    "Condition" : {
                      "Bool" : {
                        "kms:GrantIsForAWSResource" : "true"
                      }
                    }
                  } ]
                }
            KeySpec: "SYMMETRIC_DEFAULT"
            Tags: 
              - 
                Key: "PROJ"
                Value: "ECS"
            MultiRegion: false