AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    ECRRepository:
        Type: "AWS::ECR::Repository"
        Properties:
          RepositoryName: "amazon"
          EncryptionConfiguration:
            EncryptionType: "KMS"
            KmsKey: "arn:aws:kms:us-east-1:495872157039:alias/ECR_KEY"